FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml .
RUN uv sync --no-dev --no-install-project

COPY src/ ./src/

CMD [".venv/bin/uvicorn", "asgi:app", "--host", "0.0.0.0", "--port", "8550", "--app-dir", "src"]
