"""add categorization rules table

Revision ID: 67d3fa7eb3fe
Revises: 7ed2c67e5a11
Create Date: 2026-07-23 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d3fa7eb3fe'
down_revision: Union[str, None] = '7ed2c67e5a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorization_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('envelope_id', sa.Uuid(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['budget.envelopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_categorization_rules_envelope_id'), 'categorization_rules', ['envelope_id'], unique=False, schema='budget')
    op.create_index(op.f('ix_budget_categorization_rules_phrase'), 'categorization_rules', ['phrase'], unique=False, schema='budget')
    op.create_index(op.f('ix_budget_categorization_rules_user_id'), 'categorization_rules', ['user_id'], unique=False, schema='budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_categorization_rules_user_id'), table_name='categorization_rules', schema='budget')
    op.drop_index(op.f('ix_budget_categorization_rules_phrase'), table_name='categorization_rules', schema='budget')
    op.drop_index(op.f('ix_budget_categorization_rules_envelope_id'), table_name='categorization_rules', schema='budget')
    op.drop_table('categorization_rules', schema='budget')
    # ### end Alembic commands ###
