"""add upload status/storage fields to statements

Revision ID: 7ed2c67e5a11
Revises: a86741af29f4
Create Date: 2026-07-22 20:24:07.602730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed2c67e5a11'
down_revision: Union[str, None] = 'a86741af29f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('status', sa.Enum('pending', 'parsed', 'failed', name='filetransferstatus', native_enum=False), nullable=True), schema='transactions')
    op.add_column('statements', sa.Column('storage_path', sa.String(), nullable=True), schema='transactions')
    op.add_column('statements', sa.Column('size_bytes', sa.Integer(), nullable=True), schema='transactions')
    op.add_column('statements', sa.Column('error_message', sa.String(), nullable=True), schema='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'error_message', schema='transactions')
    op.drop_column('statements', 'size_bytes', schema='transactions')
    op.drop_column('statements', 'storage_path', schema='transactions')
    op.drop_column('statements', 'status', schema='transactions')
    # ### end Alembic commands ###
