"""initial budget and transactions schema tables

Revision ID: a86741af29f4
Revises: 
Create Date: 2026-07-19 22:00:19.600036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86741af29f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Schemas are normally created up front by
    # infra/postgres/init/01_create_schemas.sql when the docker-compose
    # postgres volume is first initialized. Creating them here too (idempotently)
    # means `alembic upgrade head` also works standalone, against a plain
    # Postgres instance that never ran that init script.
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS budget")
    op.execute("CREATE SCHEMA IF NOT EXISTS transactions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('checking', 'savings', 'credit_card', 'cash', name='accounttype', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_accounts_user_id'), 'accounts', ['user_id'], unique=False, schema='budget')
    op.create_table('category_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_category_groups_user_id'), 'category_groups', ['user_id'], unique=False, schema='budget')
    op.create_table('payees',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_payees_user_id'), 'payees', ['user_id'], unique=False, schema='budget')
    op.create_table('envelopes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_group_id'], ['budget.category_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_envelopes_category_group_id'), 'envelopes', ['category_group_id'], unique=False, schema='budget')
    op.create_index(op.f('ix_budget_envelopes_user_id'), 'envelopes', ['user_id'], unique=False, schema='budget')
    op.create_table('statements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format', sa.Enum('csv', 'mt940', 'ofx', name='fileformat', native_enum=False), nullable=False),
    sa.Column('imported_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['budget.accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='transactions'
    )
    op.create_index(op.f('ix_transactions_statements_account_id'), 'statements', ['account_id'], unique=False, schema='transactions')
    op.create_index(op.f('ix_transactions_statements_user_id'), 'statements', ['user_id'], unique=False, schema='transactions')
    op.create_table('envelope_allocations',
    sa.Column('envelope_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('assigned_amount', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['budget.envelopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('envelope_id', 'month'),
    schema='budget'
    )
    op.create_index(op.f('ix_budget_envelope_allocations_envelope_id'), 'envelope_allocations', ['envelope_id'], unique=False, schema='budget')
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('envelope_id', sa.Uuid(), nullable=True),
    sa.Column('payee_id', sa.Uuid(), nullable=True),
    sa.Column('statement_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('cleared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('categorization_source', sa.Enum('rule', 'ml', 'manual', name='categorizationsource', native_enum=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['budget.accounts.id'], ),
    sa.ForeignKeyConstraint(['envelope_id'], ['budget.envelopes.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['budget.payees.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['transactions.statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='transactions'
    )
    op.create_index(op.f('ix_transactions_transactions_account_id'), 'transactions', ['account_id'], unique=False, schema='transactions')
    op.create_index(op.f('ix_transactions_transactions_envelope_id'), 'transactions', ['envelope_id'], unique=False, schema='transactions')
    op.create_index(op.f('ix_transactions_transactions_payee_id'), 'transactions', ['payee_id'], unique=False, schema='transactions')
    op.create_index(op.f('ix_transactions_transactions_statement_id'), 'transactions', ['statement_id'], unique=False, schema='transactions')
    op.create_index(op.f('ix_transactions_transactions_user_id'), 'transactions', ['user_id'], unique=False, schema='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transactions_user_id'), table_name='transactions', schema='transactions')
    op.drop_index(op.f('ix_transactions_transactions_statement_id'), table_name='transactions', schema='transactions')
    op.drop_index(op.f('ix_transactions_transactions_payee_id'), table_name='transactions', schema='transactions')
    op.drop_index(op.f('ix_transactions_transactions_envelope_id'), table_name='transactions', schema='transactions')
    op.drop_index(op.f('ix_transactions_transactions_account_id'), table_name='transactions', schema='transactions')
    op.drop_table('transactions', schema='transactions')
    op.drop_index(op.f('ix_budget_envelope_allocations_envelope_id'), table_name='envelope_allocations', schema='budget')
    op.drop_table('envelope_allocations', schema='budget')
    op.drop_index(op.f('ix_transactions_statements_user_id'), table_name='statements', schema='transactions')
    op.drop_index(op.f('ix_transactions_statements_account_id'), table_name='statements', schema='transactions')
    op.drop_table('statements', schema='transactions')
    op.drop_index(op.f('ix_budget_envelopes_user_id'), table_name='envelopes', schema='budget')
    op.drop_index(op.f('ix_budget_envelopes_category_group_id'), table_name='envelopes', schema='budget')
    op.drop_table('envelopes', schema='budget')
    op.drop_index(op.f('ix_budget_payees_user_id'), table_name='payees', schema='budget')
    op.drop_table('payees', schema='budget')
    op.drop_index(op.f('ix_budget_category_groups_user_id'), table_name='category_groups', schema='budget')
    op.drop_table('category_groups', schema='budget')
    op.drop_index(op.f('ix_budget_accounts_user_id'), table_name='accounts', schema='budget')
    op.drop_table('accounts', schema='budget')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
